### ISSUE TITLE
Add login/registration logic

### ISSUE THREAD

**Issue by f1nzer** [Squesh/Deloris-server#5]

**Comment by IgorPerikov** [comment]
https://github.com/Squesh/Deloris-server/commit/3ae83cebe80ea7d1d55b952b048b3d666d32a99c
?

**Comment by f1nzer** [comment]
This issue was created in order to track progress.
For now we need better implementation of hashPassword. :+1:

**Comment by IgorPerikov** [comment]
sha256 hash - https://github.com/Squesh/Deloris-server/commit/fafd24c96d9a9edceff326abfa883f787d3456c6

**Comment by f1nzer** [comment]
Salt should be added.

**Comment by IgorPerikov** [comment]
salt:
https://github.com/Squesh/Deloris-server/commit/d072ddeefc260dda5a85f00847abdca20590802f
https://github.com/Squesh/Deloris-server/commit/1b598ad8a02a3790ce44e86844184d5fca0d3acf

**Comment by IgorPerikov** [comment]
closing as too old
